package dev.remod.installer.install;

import dev.remod.common.io.IOUtil;
import dev.remod.common.json.Json;
import dev.remod.common.json.JsonObject;
import dev.remod.common.log.ReModLog;
import dev.remod.common.log.ReModLogger;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The ReMod jars carried inside {@code ReMod.jar} and installed as Minecraft
 * libraries.
 *
 * <p>Packaging the module jars as resources rather than downloading them at
 * install time is a deliberate choice: installing ReMod then needs no network
 * at all, the installed jars are exactly the ones that shipped, and there is no
 * repository for a download to fail against.</p>
 *
 * <p>The index is generated by the build, so the list here can never drift from
 * what is actually bundled.</p>
 */
public final class BundledLibraries {

    private static final ReModLogger LOG = ReModLog.get("ReMod/Install");

    /** Where the build places the bundled jars inside {@code ReMod.jar}. */
    public static final String RESOURCE_ROOT = "/remod-libs/";

    /** The generated index listing what is bundled. */
    public static final String INDEX_RESOURCE = RESOURCE_ROOT + "index.json";

    private final List<Library> libraries;
    private final String developerApiJar;

    private BundledLibraries(List<Library> libraries, String developerApiJar) {
        this.libraries = Collections.unmodifiableList(libraries);
        this.developerApiJar = developerApiJar;
    }

    /**
     * Reads the index from the running jar.
     *
     * @throws InstallException when {@code ReMod.jar} was built without its
     *         libraries, which would otherwise produce a profile that cannot start
     */
    public static BundledLibraries load() {
        try (InputStream in = BundledLibraries.class.getResourceAsStream(INDEX_RESOURCE)) {
            if (in == null) {
                throw new InstallException(
                        "This ReMod.jar does not contain its own libraries.",
                        "Rebuild ReMod with './gradlew build', which produces the complete"
                                + " ReMod.jar in remod-dist/build/libs/.");
            }
            JsonObject root = Json.parseObject(
                    new String(IOUtil.readAll(in), StandardCharsets.UTF_8));
            List<Library> found = new ArrayList<>();
            for (JsonObject entry : root.optArray("libraries").objects()) {
                found.add(new Library(
                        entry.getString("group"),
                        entry.getString("artifact"),
                        entry.getString("version"),
                        entry.getString("file")));
            }
            if (found.isEmpty()) {
                throw new InstallException("The bundled library index is empty.",
                        "Rebuild ReMod with './gradlew build'.");
            }
            return new BundledLibraries(found, root.optString("developerApiJar", null));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read " + INDEX_RESOURCE, e);
        }
    }

    /** Builds an index explicitly. Used by tests. */
    public static BundledLibraries of(List<Library> libraries) {
        return of(libraries, null);
    }

    /** Builds an index explicitly, including the developer API jar. Used by tests. */
    public static BundledLibraries of(List<Library> libraries, String developerApiJar) {
        return new BundledLibraries(new ArrayList<>(libraries), developerApiJar);
    }

    public List<Library> libraries() {
        return libraries;
    }

    /**
     * The name of the self-contained jar mod authors compile against, or
     * {@code null} when this build does not carry one.
     *
     * <p>Distinct from the {@code remod-api} library above: that one is placed
     * on the game's classpath, where {@code remod-common} is a separate jar.
     * This one merges the two, so a mod project needs a single file dependency
     * to compile.</p>
     */
    public String developerApiJar() {
        return developerApiJar;
    }

    /**
     * Copies the developer API jar to {@code target}.
     *
     * @return false when this build carries no developer API jar
     */
    public boolean installDeveloperApi(Path target) throws IOException {
        if (developerApiJar == null) {
            return false;
        }
        try (InputStream in = BundledLibraries.class.getResourceAsStream(
                RESOURCE_ROOT + developerApiJar)) {
            if (in == null) {
                LOG.warn("The developer API jar " + developerApiJar
                        + " is named in the index but missing from ReMod.jar");
                return false;
            }
            IOUtil.writeAtomically(target, IOUtil.readAll(in));
            return true;
        }
    }

    /**
     * Copies every bundled jar into the Minecraft libraries directory, using
     * the Maven layout the launcher expects.
     *
     * @return the number of files written
     */
    public int installInto(Path librariesDirectory) throws IOException {
        int written = 0;
        for (Library library : libraries) {
            Path target = librariesDirectory.resolve(library.relativePath());
            Files.createDirectories(target.getParent());
            try (InputStream in = BundledLibraries.class.getResourceAsStream(
                    RESOURCE_ROOT + library.fileName())) {
                if (in == null) {
                    throw new InstallException("The bundled library "
                            + library.fileName() + " is missing from ReMod.jar.",
                            "Rebuild ReMod with './gradlew build'.");
                }
                byte[] bytes = IOUtil.readAll(in);
                // Skip an identical rewrite so reinstalling is cheap and does
                // not disturb a file another profile may be using.
                if (Files.exists(target) && Files.size(target) == bytes.length) {
                    LOG.debug(() -> "Library " + library.fileName() + " is already installed");
                    continue;
                }
                IOUtil.writeAtomically(target, bytes);
                written++;
                LOG.debug(() -> "Installed library " + library.relativePath());
            }
        }
        return written;
    }

    /** One bundled jar. */
    public static final class Library {

        private final String group;
        private final String artifact;
        private final String version;
        private final String fileName;

        public Library(String group, String artifact, String version, String fileName) {
            this.group = group;
            this.artifact = artifact;
            this.version = version;
            this.fileName = fileName;
        }

        public String group() {
            return group;
        }

        public String artifact() {
            return artifact;
        }

        public String version() {
            return version;
        }

        public String fileName() {
            return fileName;
        }

        /** The Maven coordinate the launcher's version JSON uses. */
        public String coordinate() {
            return group + ":" + artifact + ":" + version;
        }

        /** The path under {@code libraries/}, in Maven layout. */
        public String relativePath() {
            return group.replace('.', '/') + "/" + artifact + "/" + version + "/" + fileName;
        }

        @Override
        public String toString() {
            return coordinate();
        }
    }
}
